/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnosr;

/**
 *
 * @author arace
 */
public class Viewdos extends javax.swing.JFrame {
    private ArraAlum alumnos;

    /**
     * Creates new form Viewdos
     */
    public Viewdos() {
        initComponents();
         this.alumnos=new ArraAlum();
        System.out.println(this.alumnos.sizeListaAlumno());
        String cantidad = String.valueOf(this.alumnos.sizeListaAlumno());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnespe = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRetoRe = new javax.swing.JToggleButton();
        consul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 60));

        btnespe.setText("Especifico");
        btnespe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespeActionPerformed(evt);
            }
        });
        jPanel1.add(btnespe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 210));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 180, 210));

        btnRetoRe.setText("Regresar");
        btnRetoRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetoReActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetoRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        consul.setText("Consulta");
        consul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulActionPerformed(evt);
            }
        });
        jPanel1.add(consul, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetoReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetoReActionPerformed
        // TODO add your handling code here:
        AlumnosR.alumnos.size();
                ViewRegistro van = new ViewRegistro();
                //van.setListaAlumno();
        van.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetoReActionPerformed

    private void btnespeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespeActionPerformed
        // TODO add your handling code here:
        AlumnosR.alumnos.size();
          ViewEspecifico Esp=new ViewEspecifico();
        Esp.setVisible(true);
dispose();
    }//GEN-LAST:event_btnespeActionPerformed

    private void consulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulActionPerformed
        // TODO add your handling code here:
        
        AlumnosR.alumnos.size();
        ViewConsulta c= new ViewConsulta();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_consulActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRetoRe;
    private javax.swing.JToggleButton btnespe;
    private javax.swing.JButton consul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
