/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnosr;

import javax.swing.JOptionPane;

/**
 *
 * @author arace
 */
public class ViewEspecifico extends javax.swing.JFrame {
ArraAlum lista;
    int index=0;
    /**
     * Creates new form ViewEspecifico
     */
 
  public ViewEspecifico() {
        initComponents();

        String cantidad=String.valueOf(AlumnosR.alumnos.size());
        this.Numero.setText(cantidad);
        this.agregar();
    }
  
  public void agregar()
  {
      for (Alumno alumno : AlumnosR.alumnos) {
        int matricula = alumno.getMatricula();
        Matricula.addItem(String.valueOf(matricula));
    }
   
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Informacion = new javax.swing.JTextArea();
        Regresar = new javax.swing.JButton();
        Numero = new javax.swing.JLabel();
        Matricula = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 70, 40));

        Informacion.setColumns(20);
        Informacion.setRows(5);
        jScrollPane1.setViewportView(Informacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 440, 180));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 10, 80, 30));

        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 220, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
         //AlumnosR.alumnos.size();
       this.setVisible(false);
        Viewdos menu = new Viewdos();
        menu.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
   String matriculaSeleccionadaStr = (String) Matricula.getSelectedItem();
    
    if (matriculaSeleccionadaStr != null) {
        int matriculaSeleccionada = Integer.parseInt(matriculaSeleccionadaStr); // Convertir a Integer
        
        // Buscar al alumno por matrícula en AlumnosR.alumnos
        for (int i = 0; i < AlumnosR.alumnos.size(); i++) {
            int matriculaAlumno = AlumnosR.alumnos.get(i).getMatricula();
            if (matriculaSeleccionada == matriculaAlumno) {
                // Mostrar la información del alumno encontrado
                Informacion.setText(AlumnosR.alumnos.get(i).toString());
                this.index = i; // Guardar el índice del alumno encontrado
                return;
            }
        }
        
        JOptionPane.showMessageDialog(this, "Alumno no encontrado");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextArea Informacion;
    private javax.swing.JComboBox<String> Matricula;
    private javax.swing.JLabel Numero;
    private javax.swing.JButton Regresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
