/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnosr;

import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author arace
 */
public class ViewCambio extends javax.swing.JFrame {
   ArraAlum lista;
        int index;
        Alumno alumno;

    /**
     * Creates new form ViewCambio
     */
    public ViewCambio() {
        initComponents();
            this.lista = new ArraAlum();
          
 
    }
    
   public ViewCambio(ArraAlum lis, int in) {
        initComponents();
        this.lista = lis;
            this.index = in;

            this.Nombre.setText(this.lista.getAlumno(this.index).getNombre());
            this.Paterno.setText(this.lista.getAlumno(this.index).getAp());
            this.Materno.setText(this.lista.getAlumno(this.index).getAm());
            this.Fem.setSelected(this.lista.getAlumno(this.index).getSexo()=="Femenino");
            this.Mas.setSelected(this.lista.getAlumno(this.index).getSexo()=="Masculino");
            this.Nacimiento.setText(this.lista.getAlumno(this.index).getFecha());
            this.Matricula.setText(this.lista.getAlumno(this.index).getPrograma().getMatricula());
            this.ProgramaAcademico.setSelectedItem(this.lista.getAlumno(this.index).getProgramaacademico().toString());
            //this.Estatus.setSelected(this.lista.getAlumno(this.index).getEstatus().isSelected();
            Boolean estatus = this.Estatus.isSelected();
      //this.Matricula.setText(this.lista.getAlumno(this.index).getPrograma().getMatricula());
            //this.ProgramaAcademico.setSelectedItem(this.lista.getAlumno(this.index).getPrograma().getNombre_programa());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Materno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Fem = new javax.swing.JRadioButton();
        Mas = new javax.swing.JRadioButton();
        Nacimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Estatus = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        ProgramaAcademico = new javax.swing.JComboBox<>();
        Actualizar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Paterno = new javax.swing.JTextField();
        txtIndex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 70));

        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre(*)"));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 50));

        Materno.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido materno(*)"));
        jPanel1.add(Materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, 50));

        jLabel2.setText("Sexo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Sexo.add(Fem);
        Fem.setText("Femenino");
        jPanel1.add(Fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        Sexo.add(Mas);
        Mas.setText("Masculino");
        jPanel1.add(Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        Nacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento(*)"));
        jPanel1.add(Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 40));

        jLabel3.setText("YYYY-MM-DD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        Estatus.setText("Estatus");
        jPanel1.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ingenieria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        Matricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula(*)"));
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, -1));

        ProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en TI", "Ingenieria Mecatronica", "Ingenieria Automotriz" }));
        ProgramaAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder("Programa Academico"));
        jPanel1.add(ProgramaAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 373, -1, 20));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        Paterno.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido paterno(*)"));
        jPanel1.add(Paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, 50));

        txtIndex.setBorder(javax.swing.BorderFactory.createTitledBorder("ingresa"));
        jPanel1.add(txtIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 352, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
         String nombre = this.Nombre.getText();
       String ap=this.Paterno.getText();
       String am=this.Materno.getText();
       String sexo =((this.Fem.isSelected()) ? "Femenino"  :"Masculino");
       Boolean estatus = this.Estatus.isSelected();
       String fecha = this.Nacimiento.getText();
        //this.Matricula.setText(this.lista.getAlumno(this.index).getPrograma().getMatricula());
       int matri = parseInt(this.Matricula.getText());
       String programaacademico = this.ProgramaAcademico.getSelectedItem().toString();
       
          int index = Integer.parseInt(txtIndex.getText());
            if (index >= 0 && index < lista.sizeListaAlumno()) {
      Alumno alumnoActual = lista.getAlumno(index);
       alumnoActual.setNombre(Nombre.getText());
                alumnoActual.setAp(Paterno.getText());
                alumnoActual.setAm(Materno.getText());
                alumnoActual.setSexo(((this.Fem.isSelected()) ? "Femenino"  :"Masculino"));
                alumnoActual.setFecha(Nacimiento.getText());
                
                alumnoActual.setMatricula(Integer.parseInt(Matricula.getText()));
                alumnoActual.setProgramaacademico(ProgramaAcademico.getSelectedItem().toString());
                 
                
                // Actualizar el alumno en la lista
                lista.setAlumno(index, alumnoActual);
                
               JOptionPane.showMessageDialog(null, "Alumno actualizado correctamente");
            }else
            {
                JOptionPane.showMessageDialog(null, "Índice fuera de rango");
            }
            
    }//GEN-LAST:event_ActualizarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
         AlumnosR.alumnos.size();
        Viewdos vi=new Viewdos();
        vi.setVisible(true);
dispose();
    }//GEN-LAST:event_RegresarActionPerformed
/*public boolean modificaralu(Alumno alumno)
    {
        boolean encontrado=false;
        for(int i=0; i<this.lista.sizeListaAlumno() ; i++){

            if(this.lista.getAlumno(i).equals(i))
                    {
                     encontrado=true; 
                     lista.getAlumno(i).setNombre(alumno.getNombre());
                   lista.getAlumno(i).setAp(alumno.getAp());
                   lista.getAlumno(i).setAm(alumno.getAm());
                   lista.getAlumno(i).setFecha(alumno.getFecha());
                   lista.getAlumno(i).setSexo(alumno.getSexo());
                   lista.getAlumno(i).setEstatus(alumno.getEstatus());
                   lista.getAlumno(i).setProgramaacademico(alumno.getProgramaacademico());
                    }
            
       
        }
        return encontrado;
    }*/
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JCheckBox Estatus;
    private javax.swing.JRadioButton Fem;
    private javax.swing.JRadioButton Mas;
    private javax.swing.JTextField Materno;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Nacimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Paterno;
    private javax.swing.JComboBox<String> ProgramaAcademico;
    private javax.swing.JButton Regresar;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel num;
    private javax.swing.JTextField txtIndex;
    // End of variables declaration//GEN-END:variables
}
