/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnosr;

import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author arace
 */
public class ViewRegistro extends javax.swing.JFrame {
    private Alumno alumno;
    private ArraAlum alumnos;
       //public static  ArrayList<Alumno> alumnos = new ArrayList<>();

    /**
     * Creates new form ViewRegistro
     */
    public ViewRegistro() {
        initComponents();
        //this.lista = new ArraAlum();
        this.alumnos=new ArraAlum();
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Paterno = new javax.swing.JTextField();
        Materno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fem = new javax.swing.JRadioButton();
        Mas = new javax.swing.JRadioButton();
        Nacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Matricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ProgramaAcademico = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        Restablecer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Estatus = new javax.swing.JCheckBox();
        Datos_Guardar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO ALUMNO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Datos Personales del Alumno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre(*)"));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, -1));

        Paterno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Apellido Paterno(*)")));
        jPanel1.add(Paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, -1));

        Materno.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido Materno(*)"));
        Materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaternoActionPerformed(evt);
            }
        });
        jPanel1.add(Materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Sexo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Sexo.add(Fem);
        Fem.setText("Femenino");
        Fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemActionPerformed(evt);
            }
        });
        jPanel1.add(Fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        Sexo.add(Mas);
        Mas.setText("Masculino");
        Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasActionPerformed(evt);
            }
        });
        jPanel1.add(Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        Nacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento(*)"));
        jPanel1.add(Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 180, -1));

        jLabel4.setText("YYYY-MM-DD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 700, 10));

        Matricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula(*)"));
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ingenieria");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        ProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en TI", "Ingenieria Mecatronica", "Ingenieria Automotriz" }));
        ProgramaAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder("Programa Academico"));
        jPanel1.add(ProgramaAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        Restablecer.setText("Restablecer");
        Restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestablecerActionPerformed(evt);
            }
        });
        jPanel1.add(Restablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jButton3.setText("Ver info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        Estatus.setText("Estado");
        jPanel1.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));
        jPanel1.add(Datos_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 410, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemActionPerformed

    private void MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasActionPerformed

    private void MaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaternoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
            if (Nombre.getText().isEmpty() || Paterno.getText().isEmpty() || Materno.getText().isEmpty() || Nacimiento.getText().isEmpty() || Matricula.getText().isEmpty() || ProgramaAcademico.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(null, "Todos los campos obligatorios deben ser llenados", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }
      
       int id = AlumnosR.alumnos.size();    
       String nombre = this.Nombre.getText();
       String ap=this.Paterno.getText();
       String am=this.Materno.getText();
       String sexo =((this.Fem.isSelected()) ? "Femenino"  :"Masculino");
       
       Boolean estatus = this.Estatus.isSelected();
       String fecha = this.Nacimiento.getText();
       int matri = parseInt(this.Matricula.getText());
       String programaacademico = this.ProgramaAcademico.getSelectedItem().toString();
       LocalDate fechaNacimiento = LocalDate.parse(fecha, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
       int edad = calcularEdad(fechaNacimiento);
       
       
       Alumno alumno=new Alumno(id,nombre,  ap,  am, sexo,  fecha, programaacademico, matri, estatus, edad);
       AlumnosR.alumnos.add(alumno);
        System.out.println(alumnos.isEmptyListaAlumno());
        System.out.println(alumnos.sizeListaAlumno());
        //AlumnosR.alumnos.size();
        Viewdos vmd = new Viewdos();
       
        vmd.setVisible(true);

    }//GEN-LAST:event_GuardarActionPerformed

    

    private void RestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestablecerActionPerformed
this.Nombre.setText("");
        this.Paterno.setText("");
        this.Materno.setText("");
        this.Sexo.isSelected(null);
        this.Estatus.isSelected();
        this.Nacimiento.setText("");
        this.Matricula.setText("");
        this.Datos_Guardar.setText("");        
    }//GEN-LAST:event_RestablecerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AlumnosR.alumnos.size();
        Viewdos vi=new Viewdos();
        vi.setVisible(true);
        
dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

       private int calcularEdad(LocalDate fechaNacimiento) {
        LocalDate hoy = LocalDate.now();
        return Period.between(fechaNacimiento, hoy).getYears();
    }
        
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Datos_Guardar;
    private javax.swing.JCheckBox Estatus;
    private javax.swing.JRadioButton Fem;
    private javax.swing.JButton Guardar;
    private javax.swing.JRadioButton Mas;
    private javax.swing.JTextField Materno;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Nacimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Paterno;
    private javax.swing.JComboBox<String> ProgramaAcademico;
    private javax.swing.JButton Restablecer;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
