/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnosr;

import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author arace
 */
public class ViewConsulta extends javax.swing.JFrame {
    ArraAlum lista;
    int index=0;
    public static ArrayList<Alumno> alumnos=new ArrayList<>();
    DefaultTableModel dt=new DefaultTableModel();
  //private Alumno alumno;
    //private ArraAlum lista;
    /**
     * Creates new form ViewConsulta
     */
    public ViewConsulta() {
        initComponents();
        //this.lista = new ArraAlum();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        Eliminae = new javax.swing.JButton();
        Regre = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Paterno = new javax.swing.JTextField();
        Materno = new javax.swing.JTextField();
        Fem = new javax.swing.JRadioButton();
        Mas = new javax.swing.JRadioButton();
        Nacimiento = new javax.swing.JTextField();
        Estatus = new javax.swing.JCheckBox();
        Matricula = new javax.swing.JTextField();
        ProgramaAcademico = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Paterno", "Materno", "Sexo", "Nacimiento", "Edad", "Estatus", "Matricula", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 610, 280));

        Eliminae.setText("Eliminar");
        Eliminae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaeActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminae, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 110, 30));

        Regre.setText("Regresar");
        Regre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegreActionPerformed(evt);
            }
        });
        jPanel1.add(Regre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel2.setText("Apellido P");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel3.setText("Apellido M");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel4.setText("Sexo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel5.setText("Nacimiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel7.setText("Estatus");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 20));

        jLabel8.setText("Matricula");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre(*)"));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 190, -1));

        Paterno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Apellido Paterno(*)")));
        jPanel1.add(Paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 190, -1));

        Materno.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido Materno(*)"));
        Materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaternoActionPerformed(evt);
            }
        });
        jPanel1.add(Materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 190, -1));

        Sexo.add(Fem);
        Fem.setText("Femenino");
        Fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemActionPerformed(evt);
            }
        });
        jPanel1.add(Fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        Sexo.add(Mas);
        Mas.setText("Masculino");
        Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasActionPerformed(evt);
            }
        });
        jPanel1.add(Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        Nacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento(*)"));
        jPanel1.add(Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 180, -1));

        Estatus.setText("Estado");
        jPanel1.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        Matricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula(*)"));
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 160, -1));

        ProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en TI", "Ingenieria Mecatronica", "Ingenieria Automotriz" }));
        ProgramaAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder("Programa Academico"));
        jPanel1.add(ProgramaAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaeActionPerformed
        
        eliminarAlumno();
    
    }//GEN-LAST:event_EliminaeActionPerformed

    private void RegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegreActionPerformed
        // TODO add your handling code here:
        //AlumnosR.alumnos.size();
        this.setVisible(false);
        Viewdos menu = new Viewdos();
        menu.setVisible(true);
    }//GEN-LAST:event_RegreActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
         //this.setVisible(false);
       int selectedRow = tablaPersonas.getSelectedRow(); // Obtiene la fila seleccionada en la tabla
         String nombre = this.Nombre.getText();
          String ap=this.Paterno.getText();
       String am=this.Materno.getText();
       String sexo =((this.Fem.isSelected()) ? "Femenino"  :"Masculino");
       Boolean estatus = this.Estatus.isSelected();
       String fecha = this.Nacimiento.getText();
        //this.Matricula.setText(this.lista.getAlumno(this.index).getPrograma().getMatricula());
       int matri = parseInt(this.Matricula.getText());
       String programaacademico = this.ProgramaAcademico.getSelectedItem().toString();
       
         if (selectedRow >= 0) {
         Alumno alumnoactual= AlumnosR.alumnos.get(index);
         alumnoactual.setNombre(nombre);
         alumnoactual.setAp(Paterno.getText());
                alumnoactual.setAm(Materno.getText());
                alumnoactual.setSexo(((this.Fem.isSelected()) ? "Femenino"  :"Masculino"));
                alumnoactual.setFecha(Nacimiento.getText());
                alumnoactual.setMatricula(Integer.parseInt(Matricula.getText()));
                alumnoactual.setProgramaacademico(ProgramaAcademico.getSelectedItem().toString());
         AlumnosR.alumnos.set(index,alumnoactual);
         JOptionPane.showMessageDialog(null, "Alumno actualizado correctamente");
         }
         
   
       
    }//GEN-LAST:event_ActualizarActionPerformed

    private void MaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaternoActionPerformed

    private void FemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemActionPerformed

    private void MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasActionPerformed

    private void setupTableModel()
    {
        tablaPersonas.setModel(new DefaultTableModel(
        new Object [][]{},
       new String[]{"Nombre","Paterno","Materno","Sexo","Nacimiento","Edad","Estatus","Matricula","Carrera"}
                
        ));
    }
    private void llenarTabla()
{
    DefaultTableModel dt =new DefaultTableModel(new String[]{"Nombre","Paterno","Materno","Sexo","Nacimiento","Edad","Estatus","Matricula","Carrera"},AlumnosR.alumnos.size());
    tablaPersonas.setModel(dt);
    
    TableModel modeloDatos=tablaPersonas.getModel();
    
    for(int i=0;i<AlumnosR.alumnos.size();i++)
    {
      Alumno alumno = AlumnosR.alumnos.get(i);
      //modeloDatos.setValueAt(alumno.getNombre(),i,0);
      modeloDatos.setValueAt(alumno.getNombre(),i,0);
      modeloDatos.setValueAt(alumno.getAp(),i,1);
      modeloDatos.setValueAt(alumno.getAm(),i,2);
      modeloDatos.setValueAt(alumno.getSexo(),i,3);
      modeloDatos.setValueAt(alumno.getFecha(),i,4);
      modeloDatos.setValueAt(alumno.getEdad(),i,5);
      modeloDatos.setValueAt(alumno.getEstatus(),i,6);
      modeloDatos.setValueAt(alumno.getMatricula(),i,7);
      modeloDatos.setValueAt(alumno.getProgramaacademico(),i,8);
      //modeloDatos.setValueAt(alumno.getNombre(),i,0);
      
    }
    
    
}
    private void eliminarAlumno() {
    int selectedRow = tablaPersonas.getSelectedRow(); // Obtiene la fila seleccionada en la tabla

    if (selectedRow >= 0) { // Verifica que se haya seleccionado alguna fila
        // Obtiene la matrícula como Integer directamente desde la tabla
        Integer matricula = (Integer) tablaPersonas.getValueAt(selectedRow, 5);
        // Recorre la lista de alumnos para encontrar el que coincide con la matrícula seleccionada
        JOptionPane.showMessageDialog(this,"Alumno  eliminado");
        for (int i = 0; i < AlumnosR.alumnos.size(); i++) {
            if (AlumnosR.alumnos.get(i).getMatricula().equals(matricula)) {
               AlumnosR.alumnos.remove(i); // Elimina el alumno de la lista
                break; // Termina el bucle una vez que se ha eliminado el alumno
            }
        }
        // Elimina la fila seleccionada del modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tablaPersonas.getModel();
        model.removeRow(selectedRow);
        AlumnosR.alumnos.remove(index);
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar");
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Eliminae;
    private javax.swing.JCheckBox Estatus;
    private javax.swing.JRadioButton Fem;
    private javax.swing.JRadioButton Mas;
    private javax.swing.JTextField Materno;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Nacimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Paterno;
    private javax.swing.JComboBox<String> ProgramaAcademico;
    private javax.swing.JButton Regre;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
